[build]
builder = "nixpacks"

[deploy]
startCommand = "dotnet CafeteriaApi.dll"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
ASPNETCORE_ENVIRONMENT = "Production"